# This file was generated by GoReleaser. DO NOT EDIT.
cask "bbs-mcp" do
  version "1.3.5"

  on_macos do
    on_arm do
      sha256 "5ecbd5fae74736daba77f1c5ac1396c195a845017cee25fb057d7f11716c64f3"
      url "https://github.com/harperreed/bbs-mcp/releases/download/v#{version}/bbs-mcp_#{version}_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "b5efd466432d03ba4e0c4c9104aaccf798509d85751bb50d16475e905f28a6cf"
      url "https://github.com/harperreed/bbs-mcp/releases/download/v#{version}/bbs-mcp_#{version}_Darwin_x86_64.tar.gz"
    end
  end

  name "bbs-mcp"
  desc "A lightweight message board for humans and AI agents"
  homepage "https://github.com/harperreed/bbs-mcp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bbs"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bbs"]
    end
  end

  # No zap stanza required
end
