# This file was generated by GoReleaser. DO NOT EDIT.
cask "position" do
  version "1.7.0"

  on_macos do
    on_intel do
      sha256 "0ea5dd503146dda7ecbc847caa1dde4a26e9046412e17a2594e9bb94c59e6a73"
      url "https://github.com/harperreed/position/releases/download/v#{version}/position_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "6ce722e5d3cb34a89007c938866adcea57e8d12ce5e020ea40663b082499711f"
      url "https://github.com/harperreed/position/releases/download/v#{version}/position_#{version}_Darwin_arm64.tar.gz"
    end
  end

  name "position"
  desc "Simple location tracking CLI with MCP integration"
  homepage "https://github.com/harperreed/position"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "position"

  # No zap stanza required

end
