# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BbsMcp < Formula
  desc "A lightweight message board for humans and AI agents"
  homepage "https://github.com/harperreed/bbs"
  version "1.0.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/harperreed/bbs-mcp/releases/download/v1.0.0/bbs-mcp_1.0.0_Darwin_x86_64.tar.gz"
    sha256 "eb9afbb5ceb695c8c4ae1c79ea32d4cce3b22d80c403e8e30d029a189239673d"

    def install
      bin.install "bbs"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/harperreed/bbs-mcp/releases/download/v1.0.0/bbs-mcp_1.0.0_Darwin_arm64.tar.gz"
    sha256 "6934a062ff06feba8b4f6a646e2f2e604f2955e4a8a9354f58e0322332aeafd9"

    def install
      bin.install "bbs"
    end
  end

  test do
    system "#{bin}/bbs", "version"
  end
end
