# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BbsMcp < Formula
  desc "A lightweight message board for humans and AI agents"
  homepage "https://github.com/harperreed/bbs"
  version "1.0.6"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/harperreed/bbs-mcp/releases/download/v1.0.6/bbs-mcp_1.0.6_Darwin_x86_64.tar.gz"
    sha256 "cc4612e8700d3624fb08fc87935db162bcb848c4daa4de6b4f08699f1dfb4733"

    def install
      bin.install "bbs"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/harperreed/bbs-mcp/releases/download/v1.0.6/bbs-mcp_1.0.6_Darwin_arm64.tar.gz"
    sha256 "1df636fcbeebb129e9da486ee7cd40037db77e33edd328e4ce7f0ccef84ffb68"

    def install
      bin.install "bbs"
    end
  end

  test do
    system "#{bin}/bbs", "version"
  end
end
