# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Chronicle < Formula
  desc "Timestamped logging tool with SQLite and optional project log files"
  homepage "https://github.com/harperreed/chronicle"
  version "0.1.1"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/harperreed/chronicle/releases/download/v0.1.1/chronicle_0.1.1_darwin_amd64.tar.gz"
    sha256 "a6edaa9501915606851e2abf6e6b908a7791e9e4728d6fc8265f8721ed990add"

    def install
      bin.install "chronicle"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/harperreed/chronicle/releases/download/v0.1.1/chronicle_0.1.1_darwin_arm64.tar.gz"
    sha256 "ea8f425e7ea1bb159b7cb8946a23e1912a39c18957cbb5ffd83a8a55f2110c8d"

    def install
      bin.install "chronicle"
    end
  end

  test do
    system "#{bin}/chronicle", "--help"
  end
end
