# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Chronicle < Formula
  desc "Timestamped logging tool with SQLite and optional project log files"
  homepage "https://github.com/harperreed/chronicle"
  version "1.1.1"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/harperreed/chronicle/releases/download/v1.1.1/chronicle_1.1.1_darwin_amd64.tar.gz"
    sha256 "4f156c8cd842c1c1bb209da27ec05dcad5ab53fccd8f34dfaf096fe10b02abf1"

    def install
      bin.install "chronicle"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/harperreed/chronicle/releases/download/v1.1.1/chronicle_1.1.1_darwin_arm64.tar.gz"
    sha256 "d5d9947e9c253e6feb33219bbd74dfb8c4fc0afae0d3c384e4c10897a62e40cc"

    def install
      bin.install "chronicle"
    end
  end

  test do
    system "#{bin}/chronicle", "--help"
  end
end
