# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Crm < Formula
  desc "Personal Agent Toolkit - CRM with MCP server and CLI"
  homepage "https://github.com/harperreed/pagen"
  version "1.5.1"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/harperreed/crm/releases/download/v1.5.1/crm_1.5.1_darwin_amd64.tar.gz"
    sha256 "d5dca4c514385c88f98762eb40b4b51896460a6b75a56544c85b847fb460f605"

    def install
      bin.install "pagen"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/harperreed/crm/releases/download/v1.5.1/crm_1.5.1_darwin_arm64.tar.gz"
    sha256 "922a4c36aca04989c75226c97db05215a446e03fa5a3f81aa8ee4f9566b1a23b"

    def install
      bin.install "pagen"
    end
  end

  test do
    system "#{bin}/pagen", "--version"
  end
end
