# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Digest < Formula
  desc "RSS/Atom feed tracker for humans and AI agents"
  homepage "https://github.com/harperreed/digest"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/harperreed/digest/releases/download/v0.5.0/digest_0.5.0_Darwin_x86_64.tar.gz"
      sha256 "2293434298fbf998910c54cc881c98f9bfde9b03805ace5113b5014a49e53af4"

      def install
        bin.install "digest"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/harperreed/digest/releases/download/v0.5.0/digest_0.5.0_Darwin_arm64.tar.gz"
      sha256 "67016372ec4dff85d2163ec0ba53c0980bd81055f8bcd6e78559721074a01c0e"

      def install
        bin.install "digest"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/harperreed/digest/releases/download/v0.5.0/digest_0.5.0_Linux_x86_64.tar.gz"
      sha256 "f452721adcd1d8a556722672088ecc0cea7a094953428b677438eedcff11f347"
      def install
        bin.install "digest"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/harperreed/digest/releases/download/v0.5.0/digest_0.5.0_Linux_arm64.tar.gz"
      sha256 "a8531a6466ace3e9b24eca3ecfcc68ccf0ede0b7feaac5246de14e6363289e05"
      def install
        bin.install "digest"
      end
    end
  end

  test do
    system "#{bin}/digest", "version"
  end
end
