# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Digest < Formula
  desc "RSS/Atom feed tracker for humans and AI agents"
  homepage "https://github.com/harperreed/digest"
  version "0.3.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/harperreed/digest/releases/download/v0.3.0/digest_0.3.0_Darwin_x86_64.tar.gz"
    sha256 "962f5edcf2288f83f87394f26cc51efc914b0fecc820bac4167bc013329fa79c"

    def install
      bin.install "digest"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/harperreed/digest/releases/download/v0.3.0/digest_0.3.0_Darwin_arm64.tar.gz"
    sha256 "0deeadc2ce955bc5feef51998f2b2da8cbba849bae6ad1e315758d5cfac07def"

    def install
      bin.install "digest"
    end
  end

  test do
    system "#{bin}/digest", "version"
  end
end
