# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Health < Formula
  desc "Health tracking CLI with MCP integration"
  homepage "https://github.com/harperreed/health"
  version "1.3.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/harperreed/health/releases/download/v1.3.0/health_1.3.0_Darwin_x86_64.tar.gz"
    sha256 "8055481641a08512037f0eb8910cb44447862da0b5f10bfd0ddd9c08ef6ba659"

    def install
      bin.install "health"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/harperreed/health/releases/download/v1.3.0/health_1.3.0_Darwin_arm64.tar.gz"
    sha256 "8376bdc7213f60892a19abf1032967e20f643d3ae007ada25f92406e7734d2b1"

    def install
      bin.install "health"
    end
  end

  test do
    system "#{bin}/health", "--help"
  end
end
