# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Health < Formula
  desc "Health tracking CLI with MCP integration"
  homepage "https://github.com/harperreed/health"
  version "1.2.4"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/harperreed/health/releases/download/v1.2.4/health_1.2.4_Darwin_x86_64.tar.gz"
    sha256 "763deb55d7c4d475d3a96aa275893805f19ab79b0fcd6510b88d1ccb1b50fc85"

    def install
      bin.install "health"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/harperreed/health/releases/download/v1.2.4/health_1.2.4_Darwin_arm64.tar.gz"
    sha256 "45fbbaea01f71f5292d22baa597e3f15daaddd4e09edc2f813049f135e45925d"

    def install
      bin.install "health"
    end
  end

  test do
    system "#{bin}/health", "--help"
  end
end
