# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Health < Formula
  desc "Health tracking CLI with MCP integration"
  homepage "https://github.com/harperreed/health"
  version "1.7.1"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/harperreed/health/releases/download/v1.7.1/health_1.7.1_Darwin_x86_64.tar.gz"
    sha256 "f9f0bbb7a0247924f2e8ee45e50a8996abf81affe726612cb7a13c9392a84365"

    define_method(:install) do
      bin.install "health"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/harperreed/health/releases/download/v1.7.1/health_1.7.1_Darwin_arm64.tar.gz"
    sha256 "c3fa524d6057778042a5210a86a8f310d53baf390912bc414cd5941fc8c6294e"

    define_method(:install) do
      bin.install "health"
    end
  end

  test do
    system "#{bin}/health", "--help"
  end
end
