# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Memory < Formula
  desc "HMLR - Hierarchical Memory Lookup & Routing for LLM agents"
  homepage "https://github.com/harperreed/remember-standalone"
  version "0.3.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/harperreed/memory/releases/download/v0.3.0/memory_0.3.0_Darwin_x86_64.tar.gz"
    sha256 "0aaba3745e84402f0f05b5fb68cdad9b1bf8c7f6eaa2056e7aeabe978d42c4b3"

    def install
      bin.install "memory"
      bin.install "hmlr-benchmark"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/harperreed/memory/releases/download/v0.3.0/memory_0.3.0_Darwin_arm64.tar.gz"
    sha256 "b316c295bfe520c91a84605b0e26e66c491f8617e1b2d0948cdb785c7d2f581c"

    def install
      bin.install "memory"
      bin.install "hmlr-benchmark"
    end
  end

  def caveats
    <<~EOS
      Memory uses OpenAI for embeddings and LLM features.
      Set OPENAI_API_KEY in your environment to enable full functionality.

      To use with Claude Desktop, add to claude_desktop_config.json:
      {
        "mcpServers": {
          "memory": {
            "command": "memory",
            "args": ["mcp"]
          }
        }
      }
    EOS
  end

  test do
    system "#{bin}/memory", "--help"
  end
end
