# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Memory < Formula
  desc "HMLR - Hierarchical Memory Lookup & Routing for LLM agents"
  homepage "https://github.com/harperreed/remember-standalone"
  version "0.5.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/harperreed/memory/releases/download/v0.5.0/memory_0.5.0_Darwin_x86_64.tar.gz"
    sha256 "a6719b3b1d18db2fdcec5ed4b6bce6077b604ffc632c3fc5dc4df2392d12ecf3"

    def install
      bin.install "memory"
      bin.install "hmlr-benchmark"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/harperreed/memory/releases/download/v0.5.0/memory_0.5.0_Darwin_arm64.tar.gz"
    sha256 "f5c1c33a1080471561c1cb07042dc38e08112bdf595d88b24532b3b12936c9b4"

    def install
      bin.install "memory"
      bin.install "hmlr-benchmark"
    end
  end

  def caveats
    <<~EOS
      Memory uses OpenAI for embeddings and LLM features.
      Set OPENAI_API_KEY in your environment to enable full functionality.

      To use with Claude Desktop, add to claude_desktop_config.json:
      {
        "mcpServers": {
          "memory": {
            "command": "memory",
            "args": ["mcp"]
          }
        }
      }
    EOS
  end

  test do
    system "#{bin}/memory", "--help"
  end
end
