# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Memo < Formula
  desc "A command-line notes tool with markdown, tags, and MCP support"
  homepage "https://github.com/harperreed/memo"
  version "0.1.1"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/harperreed/memo/releases/download/v0.1.1/memo_0.1.1_Darwin_x86_64.tar.gz"
    sha256 "f8d69e65fd8d3b24ebb9cc1a2d786bb6f8ae9a601fc767880c4c7bd1638c053a"

    def install
      bin.install "memo"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/harperreed/memo/releases/download/v0.1.1/memo_0.1.1_Darwin_arm64.tar.gz"
    sha256 "7d1ef5c99772a4ed0b6f181c689d3f7f43ee110614da692f1a0bdb09910fe11f"

    def install
      bin.install "memo"
    end
  end

  test do
    system "#{bin}/memo", "--help"
  end
end
