# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Memory < Formula
  desc "HMLR - Hierarchical Memory Lookup & Routing for LLM agents"
  homepage "https://github.com/harperreed/remember-standalone"
  version "0.3.4"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/harperreed/memory/releases/download/v0.3.4/memory_0.3.4_Darwin_x86_64.tar.gz"
    sha256 "5196d4f996c78ba0a27f6caeb3e63f5bc60f5fe6ff1c855329f9313833b67cb2"

    def install
      bin.install "memory"
      bin.install "hmlr-benchmark"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/harperreed/memory/releases/download/v0.3.4/memory_0.3.4_Darwin_arm64.tar.gz"
    sha256 "bdb4945e538a82cfb1f2616071bf656af6934013d212fd99ecdcb55976cb3961"

    def install
      bin.install "memory"
      bin.install "hmlr-benchmark"
    end
  end

  def caveats
    <<~EOS
      Memory uses OpenAI for embeddings and LLM features.
      Set OPENAI_API_KEY in your environment to enable full functionality.

      To use with Claude Desktop, add to claude_desktop_config.json:
      {
        "mcpServers": {
          "memory": {
            "command": "memory",
            "args": ["mcp"]
          }
        }
      }
    EOS
  end

  test do
    system "#{bin}/memory", "--help"
  end
end
