# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Memo < Formula
  desc "A command-line notes tool with markdown, tags, and MCP support"
  homepage "https://github.com/harperreed/memo"
  version "0.7.5"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/harperreed/memo/releases/download/v0.7.5/memo_0.7.5_Darwin_x86_64.tar.gz"
    sha256 "d4bde098945eb5b43e65e8b84f8feb1b1baa7e324e81f0e5143a83a122811a24"

    def install
      bin.install "memo"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/harperreed/memo/releases/download/v0.7.5/memo_0.7.5_Darwin_arm64.tar.gz"
    sha256 "52416d36338fd058e4dc7cf97806e9811c706c100fa6bf4ebd62596def7341f9"

    def install
      bin.install "memo"
    end
  end

  test do
    system "#{bin}/memo", "--help"
  end
end
