# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NotesMcp < Formula
  desc "MCP server for Apple Notes with CLI tools"
  homepage "https://github.com/harperreed/notes-mcp"
  version "0.1.0"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/harperreed/notes-mcp/releases/download/v0.1.0/notes-mcp_0.1.0_darwin_amd64.tar.gz"
    sha256 "b08872e0d73bc64a3a27c918c2e126ecb21bbcb7455538a379baf92353abe7a3"

    def install
      bin.install "mcp-apple-notes-go"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/harperreed/notes-mcp/releases/download/v0.1.0/notes-mcp_0.1.0_darwin_arm64.tar.gz"
    sha256 "c27c10d8d80e01d438a28c36c4d8bc5089368f11b543ebf72225c082344174a6"

    def install
      bin.install "mcp-apple-notes-go"
    end
  end

  test do
    system "#{bin}/mcp-apple-notes-go", "--version"
  end
end
