# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NotesMcp < Formula
  desc "MCP server for Apple Notes with CLI tools"
  homepage "https://github.com/harperreed/notes-mcp"
  version "0.1.0"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/harperreed/notes-mcp/releases/download/v0.1.0/notes-mcp_0.1.0_darwin_amd64.tar.gz"
    sha256 "9d995a3908ac04b061ff187e6fc8f1b2ef254c6d324fb5f9a58828ac0609064f"

    def install
      bin.install "notes-mcp"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/harperreed/notes-mcp/releases/download/v0.1.0/notes-mcp_0.1.0_darwin_arm64.tar.gz"
    sha256 "17582fe93e144e15e17a6b0dba2d7f9a83ca0b4d2c6bb6fca2f86a0f5f7e6a83"

    def install
      bin.install "notes-mcp"
    end
  end

  test do
    system "#{bin}/notes-mcp", "help"
  end
end
