# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NotesMcp < Formula
  desc "MCP server for Apple Notes with CLI tools"
  homepage "https://github.com/harperreed/notes-mcp"
  version "0.1.0"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/harperreed/notes-mcp/releases/download/v0.1.0/notes-mcp_0.1.0_darwin_amd64.tar.gz"
    sha256 "23033d1341288b4630088d73181c3985595292e8a1c172eae1385464b8356aaa"

    def install
      bin.install "apple-notes-mcp"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/harperreed/notes-mcp/releases/download/v0.1.0/notes-mcp_0.1.0_darwin_arm64.tar.gz"
    sha256 "83f27ec03e9cb98298af96256e317d58c81653359ced3e338145b5b1406c04ed"

    def install
      bin.install "apple-notes-mcp"
    end
  end

  test do
    system "#{bin}/apple-notes-mcp", "--version"
  end
end
