# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pagen < Formula
  desc "Personal Agent Toolkit - CRM with MCP server and CLI"
  homepage "https://github.com/harperreed/pagen"
  version "0.1.9"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/harperreed/pagen/releases/download/v0.1.9/pagen_0.1.9_darwin_amd64.tar.gz"
    sha256 "a27394cad9767358165be8e13f7c5bec357d234d492fe0af6e12b2a175f911c7"

    def install
      bin.install "pagen"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/harperreed/pagen/releases/download/v0.1.9/pagen_0.1.9_darwin_arm64.tar.gz"
    sha256 "07ac7d07ab55732b15bc8397f1d250661c3224cc23b31ac04a7021ee1cf7833d"

    def install
      bin.install "pagen"
    end
  end

  test do
    system "#{bin}/pagen", "--version"
  end
end
