# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pagen < Formula
  desc "Personal Agent Toolkit - CRM with MCP server and CLI"
  homepage "https://github.com/harperreed/pagen"
  version "0.4.4"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/harperreed/pagen/releases/download/v0.4.4/pagen_0.4.4_darwin_amd64.tar.gz"
    sha256 "25ef2ef0ace0b0171a6b7a7ae39730a76bc1a935deeecef498363face732dd1b"

    def install
      bin.install "pagen"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/harperreed/pagen/releases/download/v0.4.4/pagen_0.4.4_darwin_arm64.tar.gz"
    sha256 "fbc126aa6fc4dccffb5447cb4726cf866c72f4737e78c5e6ea70c5da62e2f710"

    def install
      bin.install "pagen"
    end
  end

  test do
    system "#{bin}/pagen", "--version"
  end
end
