# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pagen < Formula
  desc "Personal Agent Toolkit - CRM with MCP server and CLI"
  homepage "https://github.com/harperreed/pagen"
  version "0.4.1"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/harperreed/pagen/releases/download/v0.4.1/pagen_0.4.1_darwin_amd64.tar.gz"
    sha256 "4e8c40032d4d5e8023a9273bfa608f0ba33bb4fd3665efa7b75267b5306ecbff"

    def install
      bin.install "pagen"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/harperreed/pagen/releases/download/v0.4.1/pagen_0.4.1_darwin_arm64.tar.gz"
    sha256 "71fa06de96c9ccaef6cf0a15fa505619622baff8eb126c47822a95e2625964cc"

    def install
      bin.install "pagen"
    end
  end

  test do
    system "#{bin}/pagen", "--version"
  end
end
