# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pingpong < Formula
  desc "A beautiful TUI ping utility for monitoring network connectivity"
  homepage "https://github.com/harperreed/pingpong"
  version "0.1.8"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/harperreed/pingpong/releases/download/v0.1.8/pingpong_0.1.8_Darwin_x86_64.tar.gz"
    sha256 "3d8144a83504aa96c7cdcceafed1e7cae5adac4f042f197303099f4c5040cf34"

    define_method(:install) do
      bin.install "pingpong"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/harperreed/pingpong/releases/download/v0.1.8/pingpong_0.1.8_Darwin_arm64.tar.gz"
    sha256 "c2726978149c084d76b662f94c5be3779456f01039382d10b66bce9b1dc3cf4f"

    define_method(:install) do
      bin.install "pingpong"
    end
  end

  test do
    system "#{bin}/pingpong", "--help"
  end
end
