# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PushCli < Formula
  desc "CLI and MCP server for Pushover notifications"
  homepage "https://github.com/harperreed/push-cli"
  version "0.1.1"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/harperreed/push-cli/releases/download/v0.1.1/push-cli_0.1.1_Darwin_x86_64.tar.gz"
    sha256 "6658b9c2f25270d9ed55910428c3c9d80f7694c06bd34a48723d3309e963d474"

    def install
      bin.install "push"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/harperreed/push-cli/releases/download/v0.1.1/push-cli_0.1.1_Darwin_arm64.tar.gz"
    sha256 "557138467dec2c53aa18fdbccff18ad3dc398c7978457a401dae99868c9f10c3"

    def install
      bin.install "push"
    end
  end

  test do
    system "#{bin}/push", "version"
  end
end
