# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PushCli < Formula
  desc "CLI and MCP server for Pushover notifications"
  homepage "https://github.com/harperreed/push-cli"
  version "0.0.2"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/harperreed/push-cli/releases/download/v0.0.2/push-cli_0.0.2_Darwin_x86_64.tar.gz"
    sha256 "27a62398b7ed4d001bdd18d4b4ccd266ca9d512200544a7b471dfa0e6b685292"

    def install
      bin.install "push"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/harperreed/push-cli/releases/download/v0.0.2/push-cli_0.0.2_Darwin_arm64.tar.gz"
    sha256 "347bff50f4f87c4ca51e940ca56bada013782da319d60d84d3ba494026f13f8f"

    def install
      bin.install "push"
    end
  end

  test do
    system "#{bin}/push", "version"
  end
end
