# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sweet < Formula
  desc "A super simple git-aware todo manager"
  homepage "https://github.com/harperreed/sweet"
  version "0.2.1"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/harperreed/sweet/releases/download/v0.2.1/sweet_0.2.1_Darwin_x86_64.tar.gz"
    sha256 "84a5629bdce6ff990ffa2735351cad3db7d1d310b1193c2a06436de76e6702ba"

    def install
      bin.install "sweet"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/harperreed/sweet/releases/download/v0.2.1/sweet_0.2.1_Darwin_arm64.tar.gz"
    sha256 "fc1e7161fe5d0e194e901acba1099df65346a7e9ddab8837d3533b554d9a817f"

    def install
      bin.install "sweet"
    end
  end

  test do
    system "#{bin}/sweet", "version"
  end
end
