# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Toki < Formula
  desc "A super simple git-aware todo manager"
  homepage "https://github.com/harperreed/toki"
  version "0.4.1"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/harperreed/toki/releases/download/v0.4.1/toki_0.4.1_Darwin_x86_64.tar.gz"
    sha256 "9755a7cfd1cf9ba1140169a74b1b713449decf137ec5ab6f1c7e6013aa1e08a7"

    def install
      bin.install "toki"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/harperreed/toki/releases/download/v0.4.1/toki_0.4.1_Darwin_arm64.tar.gz"
    sha256 "55c154801d6b62aa5e4ffa65e969917c3c7aeed5da6b824a682b9242421d5ac6"

    def install
      bin.install "toki"
    end
  end

  test do
    system "#{bin}/toki", "version"
  end
end
