# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Toki < Formula
  desc "A super simple git-aware todo manager"
  homepage "https://github.com/harperreed/toki"
  version "0.5.3"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/harperreed/toki/releases/download/v0.5.3/toki_0.5.3_Darwin_x86_64.tar.gz"
    sha256 "be723a4c458eabe4b921197ae59f58614296470bfdf0e05fa33fdf4a421eaf79"

    def install
      bin.install "toki"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/harperreed/toki/releases/download/v0.5.3/toki_0.5.3_Darwin_arm64.tar.gz"
    sha256 "c53895d6b445f7486d7ee6bdc31465571beab1c7a4951d74dd62c1f6d2c837c2"

    def install
      bin.install "toki"
    end
  end

  test do
    system "#{bin}/toki", "version"
  end
end
